services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: insnex-frontend

networks:
  app:
    driver: bridge